/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_StartActivity */

#ifndef _Included_org_example_ndk_StartActivity
#define _Included_org_example_ndk_StartActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_ndk_StartActivity
 * Method:    openDevice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_example_ndk_StartActivity_openDevice
  (JNIEnv *, jobject);

/*
 * Class:     org_example_ndk_StartActivity
 * Method:    startGame
 * Signature: (ILorg/example/ndk/StartActivity/Arg;)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_StartActivity_startGame
  (JNIEnv *, jobject, jint, jobject);

/*
 * Class:     org_example_ndk_StartActivity
 * Method:    closeDevice
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_example_ndk_StartActivity_closeDevice
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
