/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_ndk_StartActivity_Arg */

#ifndef _Included_org_example_ndk_StartActivity_Arg
#define _Included_org_example_ndk_StartActivity_Arg
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
